### PR TITLE
Add default system config dir

### PR DESCRIPTION
**Pull request by mauromorales**
Fixes kairos-io/kairos#2221

### CODE REVIEW

**Review by jimmykarily — COMMENTED** [review]
We will need to document this. Here maybe? https://kairos.io/docs/reference/build-from-scratch/ not sure.

**Comment by Itxaka** [comment]
I dont understand this. Are we just introducing an extra dir? What does this gives us that /system/oem or /oem doesnt?

**Comment by jimmykarily** [comment]
> I dont understand this. Are we just introducing an extra dir? What does this gives us that /system/oem or /oem doesnt?

as far as I understand, this new directory is meant to be used by "vendors" to ship config along with the released images. The other paths are there for the users to place their own configs. I'm not sure why the vendors can't write to these directories. Probably because of how we mount them to persistent? (overlaying on top of the existing path)

**Review by Itxaka — APPROVED** [review]

**Comment by mauromorales** [comment]
> /etc/elemental/config.yaml was supported as a way to inject default system configs. As part of those we could configure branding menu to be applied during upgrade and reset, and additional cloud config path to look into the system.

> Now we expect all that data to come from the user-data, however, we don't have a way to specify those settings when we build the images. The config collector scans configurations exclusively in paths that are either persistent or not accessible on build time

**Pull request merged**
