### PR TITLE
:art: Use ext4 by default

### PR DESCRIPTION
**Pull request by Itxaka**
Images were being formated on ext2 for some old reason. Makes no sense to keep them that way, just move everything to ext4 by default

### CODE REVIEW

**Comment by mudler** [comment]
the reason is that ext4 has journaling. ext2 doesn't. in systems with RO-only you don't really need journaling, and that means the disk will live longer

**Comment by mudler** [comment]
that being said, I have no other strong preference here, but, would be nice to offer a parameter for that to override the default behavior at this point?

**Comment by jimmykarily** [comment]
If we need some attributes of ext4 but not journaling, it seems it's possible to just disable journaling: https://foxutech.com/how-to-disable-enable-journaling/

**Comment by Itxaka** [comment]
There is also other partitions that we use that are RO that are already on ext4, and we see no issues with that. This is just turning the default in the images to ext4 to have the same fs in all of our partitions. But we can discuss this further on monday meetings

**Pull request closed without merging**
